# 认证服务特定配置
spring:
  application:
    name: auth-service

server:
  port: 8001

mybatis-plus:
  type-aliases-package: com.dataplatform.core.auth.entity

logging:
  level:
    com.dataplatform.core.auth: debug