# 网关服务特定配置
spring:
  application:
    name: gateway-service

server:
  port: 9000

spring.cloud.gateway.routes:
  - id: auth-service
    uri: lb://auth-service
    predicates:
      - Path=/api/auth/**
  - id: audit-service
    uri: lb://audit-service
    predicates:
      - Path=/api/audit/**