spring:
  application:
    name: audit-service
  datasource:
    url: jdbc:mysql://localhost:3306/datacore_audit?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        shared-configs:
          - data-id: application-common.yaml
            group: DEFAULT_GROUP

server:
  port: 8002

spring.jpa:
  hibernate:
    ddl-auto: update
  show-sql: true

logging:
  level:
    com.dataplatform.core.audit: debug