spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: audit-service
          uri: lb://audit-service
          predicates:
            - Path=/api/audit/**

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"